disable_all_schedules:
  name: Disable All Schedules
  description: Disable all charging schedules for an Andersen EV charge point
  fields:
    device_id:
      name: Device ID
      description: The ID of the Andersen EV device to disable schedules for
      required: true
      example: "1b6f9e38a4d72c0f5e831649"
      selector:
        text: {}

get_device_info:
  name: Get Device Info
  description: Get detailed information about an Andersen EV charge point with results displayed in the UI
  fields:
    device_id:
      name: Device ID
      description: The ID of the Andersen EV device to get information for
      required: true
      example: "1b6f9e38a4d72c0f5e831649"
      selector:
        text: {}
  response:
    name: Device Information
    description: Returns detailed information about the selected Andersen EV charger

get_device_status:
  name: Get Device Status
  description: Get detailed status of an Andersen EV charge point with results displayed in the UI
  fields:
    device_id:
      name: Device ID
      description: The ID of the Andersen EV device to get status for
      required: true
      example: "1b6f9e38a4d72c0f5e831649"
      selector:
        text: {}
  response:
    name: Device Status
    description: Returns detailed status for the selected Andersen EV charger

reset_rcm:
  name: Reset RCM Fault
  description: Reset the RCM fault on an Andersen EV charge point
  fields:
    device_id:
      name: Device ID
      description: The ID of the Andersen EV device to reset RCM for
      required: true
      example: "1b6f9e38a4d72c0f5e831649"
      selector:
        text: {}